<?php
require_once dirname(__DIR__) . '/app/bootstrap.php';
require_role(['teacher', 'admin']);
$summary = [
    'learners' => (int) (Database::fetch("SELECT COUNT(*) AS total FROM users WHERE role = 'learner' AND status = 'active'")['total'] ?? 0),
    'completed' => (int) (Database::fetch("SELECT COUNT(*) AS total FROM progress WHERE status = 'completed'")['total'] ?? 0),
    'attempts' => (int) (Database::fetch('SELECT COUNT(*) AS total FROM quiz_attempts')['total'] ?? 0),
    'average' => (int) (Database::fetch('SELECT ROUND(AVG(score)) AS average FROM quiz_attempts')['average'] ?? 0),
];
$learners = Database::fetchAll("SELECT u.id, u.name, u.username, u.points, u.last_login_at, COUNT(DISTINCT CASE WHEN p.status = 'completed' THEN p.lesson_id END) AS completed_lessons, ROUND(AVG(CASE WHEN p.best_score > 0 THEN p.best_score END)) AS average_score, COUNT(DISTINCT pr.id) AS project_count FROM users u LEFT JOIN progress p ON p.user_id = u.id LEFT JOIN projects pr ON pr.user_id = u.id WHERE u.role = 'learner' GROUP BY u.id ORDER BY u.last_login_at DESC, u.name");
$difficult = Database::fetchAll('SELECT l.id, l.title, COUNT(qa.id) AS attempts, ROUND(AVG(qa.score)) AS average_score, SUM(CASE WHEN qa.passed = 0 THEN 1 ELSE 0 END) AS failed_attempts FROM lessons l LEFT JOIN quiz_attempts qa ON qa.lesson_id = l.id GROUP BY l.id HAVING COUNT(qa.id) > 0 ORDER BY average_score ASC LIMIT 5');
$pageTitle = 'Teacher dashboard'; $bodyClass = 'app-page teacher-page'; require base_path('partials/header.php');
?>
<section class="page-hero teacher-hero"><div class="container"><span class="eyebrow light">Teacher overview</span><h1>Learning activity and support needs</h1><p>Use completion and assessment evidence to identify where learners may need guidance.</p></div></section>
<section class="section"><div class="container">
<div class="dashboard-stat-grid four"><article class="metric-card"><span class="metric-icon purple">👥</span><div><strong><?= $summary['learners'] ?></strong><small>Active learners</small></div></article><article class="metric-card"><span class="metric-icon green">✓</span><div><strong><?= $summary['completed'] ?></strong><small>Lesson completions</small></div></article><article class="metric-card"><span class="metric-icon orange">📝</span><div><strong><?= $summary['attempts'] ?></strong><small>Quiz attempts</small></div></article><article class="metric-card"><span class="metric-icon blue">⭐</span><div><strong><?= $summary['average'] ?>%</strong><small>Assessment average</small></div></article></div>
<div class="teacher-grid"><section><div class="section-row"><div><span class="eyebrow">Learner overview</span><h2>Progress by learner</h2></div></div><div class="table-card"><div class="responsive-table"><table><thead><tr><th>Learner</th><th>Completed</th><th>Best-score average</th><th>Projects</th><th>Last active</th></tr></thead><tbody><?php foreach($learners as $learner):?><tr><td><strong><?=e($learner['name'])?></strong><small class="table-subtext">@<?=e($learner['username'])?> · <?=number_format((int)$learner['points'])?> points</small></td><td><?= (int)$learner['completed_lessons'] ?></td><td><?= (int)($learner['average_score']??0) ?>%</td><td><?= (int)$learner['project_count'] ?></td><td><?=e(time_ago($learner['last_login_at']))?></td></tr><?php endforeach;?></tbody></table></div></div></section>
<aside><div class="sidebar-card"><span class="eyebrow">Needs attention</span><h2>Lowest quiz averages</h2><?php if(!$difficult):?><p>No assessment data yet.</p><?php endif;?><div class="difficulty-list"><?php foreach($difficult as $item):?><a href="<?=e(url('lesson.php?id='.(int)$item['id']))?>"><div><strong><?=e($item['title'])?></strong><small><?= (int)$item['attempts'] ?> attempts · <?= (int)$item['failed_attempts'] ?> below pass mark</small></div><span><?= (int)$item['average_score'] ?>%</span></a><?php endforeach;?></div></div><div class="sidebar-card teacher-note"><span aria-hidden="true">🔎</span><h2>Interpret carefully</h2><p>Scores indicate where to ask questions. They should not be used alone to label a learner's ability.</p></div></aside></div>
</div></section>
<?php require base_path('partials/footer.php'); ?>
