<?php
require_once __DIR__ . '/app/bootstrap.php';
if (!Database::tableExists('users')) redirect('setup.php');
$stats = Learning::publicStatistics();
$pageTitle = 'About';
$pageDescription = 'How CodeMwana delivers structured, safe and database-backed programming education for children.';
$bodyClass = 'content-page';
require base_path('partials/header.php');
?>
<section class="content-hero"><div class="container content-hero-grid"><div><span class="eyebrow">Purpose-built learning platform</span><h1>Programming education designed around clear progress.</h1><p><?= e(setting('site_description', 'CodeMwana combines guided curriculum, practical coding and measurable learner progress in one responsive platform.')) ?></p></div><div class="content-hero-stats"><div><strong><?= number_format($stats['courses']) ?></strong><span>Published paths</span></div><div><strong><?= number_format($stats['lessons']) ?></strong><span>Guided lessons</span></div><div><strong><?= number_format($stats['projects']) ?></strong><span>Saved projects</span></div></div></div></section>
<section class="section"><div class="container prose-shell"><article class="panel prose-panel"><span class="eyebrow">The need</span><h2>Learning that works beyond ideal conditions</h2><p>Many beginner platforms assume constant internet access, unrestricted code execution and prior familiarity with technical language. CodeMwana uses lightweight pages, ordered lessons and a controlled beginner language so learners can focus on computational thinking without unnecessary complexity.</p><h2>How learning works</h2><p>Learners enrol in a published path, work through database-managed lessons, practise in Code Lab, answer assessment questions and receive immediate explanations. Progress, best scores, achievements and project versions remain connected to the learner account across sessions.</p><h2>Operational platform</h2><p>Teachers can review learner performance and difficult lessons. Administrators can manage accounts, curriculum, quiz questions, announcements and public settings. The public website, learner workspace and staff dashboards all read from the same relational database.</p></article><aside class="content-side"><section class="panel"><span class="eyebrow">Technical foundation</span><h2>Built for dependable operation</h2><ul class="check-list"><li>PHP 8.1+ with PDO and prepared statements</li><li>MySQL/MariaDB or SQLite persistence</li><li>Role-based access and CSRF protection</li><li>Password hashing and login rate limiting</li><li>Responsive external CSS and accessible controls</li><li>Controlled MwanaCode interpreter without eval()</li></ul></section><section class="panel"><span class="eyebrow">Coursework alignment</span><h2>ICT4410 Question 11</h2><p>The platform directly addresses the requirement to teach children basic programming skills and concepts while adding real account operations, curriculum management, reporting and persistent learner data.</p></section></aside></div></section>
<?php require base_path('partials/footer.php'); ?>
