<?php
require_once __DIR__ . '/app/bootstrap.php';
require_auth();
$user=current_user();$lesson=null;$project=null;
$starterCode="SAY \"Welcome to CodeMwana\"\nSET goal = \"Build useful ideas\"\nSAY goal";
$projectTitle='Untitled MwanaCode program';
$lessonIdentifier=(string)($_GET['lesson']??'');
if($lessonIdentifier!==''){$lesson=Learning::lesson($lessonIdentifier);if($lesson&&trim((string)$lesson['starter_code'])!==''){$starterCode=$lesson['starter_code'];$projectTitle=$lesson['title'].' challenge';}}
$projectId=request_int('project');
if($projectId){$project=Learning::project($projectId,(int)$user['id']);if($project){$starterCode=$project['code'];$projectTitle=$project['title'];}else{flash('error','That project is not available in your library.');redirect('projects.php');}}
$pageTitle='Code Lab';$bodyClass='code-lab-page';$pageScript='playground.js';require base_path('partials/header.php');
?>
<section class="code-lab-shell" data-code-lab data-save-url="<?= e(url('api/save-project.php')) ?>" data-csrf="<?= e(csrf_token()) ?>" data-project-id="<?= (int)($project['id']??0) ?>">
<div class="code-lab-toolbar"><div class="code-lab-title"><a class="icon-button" href="<?= e(url('projects.php')) ?>" aria-label="Return to project library"><?= icon('arrow-left') ?></a><div><span>MwanaCode workspace</span><input type="text" value="<?= e($projectTitle) ?>" maxlength="120" aria-label="Project title" data-project-title></div></div><div class="code-lab-actions"><span class="save-status" data-save-status><?= $project?'Saved project':'Not saved yet' ?></span><button class="button button-secondary button-small" type="button" data-reset-code>Reset code</button><button class="button button-secondary button-small" type="button" data-save-project><?= icon('save') ?>Save</button><button class="button button-small run-button" type="button" data-run-code><?= icon('play') ?>Run program</button></div></div>
<div class="code-lab-layout">
<aside class="command-panel" aria-label="MwanaCode command reference"><div class="panel-tabs"><strong>Command library</strong><button class="icon-button" type="button" data-open-guide aria-label="Open language guide"><?= icon('info') ?></button></div><div class="command-search"><?= icon('search') ?><label class="sr-only" for="command-search">Search commands</label><input id="command-search" aria-label="Search commands" data-command-search></div><div class="command-groups"><section><h2>Output</h2><button type="button" class="command-chip purple" data-insert='SAY "Hello, coder!"'><code>SAY "Hello, coder!"</code><small>Display text or a value</small></button></section><section><h2>Variables</h2><button type="button" class="command-chip blue" data-insert='SET learner = "Mwamba"'><code>SET learner = "Mwamba"</code><small>Store a value</small></button><button type="button" class="command-chip blue" data-insert='ADD points 10'><code>ADD points 10</code><small>Increase a number</small></button></section><section><h2>Control flow</h2><button type="button" class="command-chip orange" data-insert="REPEAT 4\n  SAY \"Again\"\nEND"><code>REPEAT 4 ... END</code><small>Repeat a block</small></button><button type="button" class="command-chip orange" data-insert="IF score >= 50\n  SAY \"Pass\"\nELSE\n  SAY \"Keep practising\"\nEND"><code>IF ... ELSE ... END</code><small>Make a decision</small></button></section><section><h2>Turtle drawing</h2><button type="button" class="command-chip green" data-insert="MOVE 100"><code>MOVE 100</code><small>Move and draw</small></button><button type="button" class="command-chip green" data-insert="TURN 90"><code>TURN 90</code><small>Rotate clockwise</small></button><button type="button" class="command-chip green" data-insert='PEN "#6C5CE7"'><code>PEN "#6C5CE7"</code><small>Set line colour</small></button><button type="button" class="command-chip green" data-insert="CLEAR"><code>CLEAR</code><small>Clear the canvas</small></button></section></div></aside>
<section class="editor-panel"><div class="panel-heading"><div><span class="status-dot"></span><strong>Editor</strong><small>MwanaCode</small></div><div><button type="button" class="icon-button" aria-label="Decrease editor text size" data-font-decrease>A−</button><button type="button" class="icon-button" aria-label="Increase editor text size" data-font-increase>A+</button></div></div><div class="editor-wrap"><div class="line-numbers" aria-hidden="true" data-line-numbers></div><textarea spellcheck="false" aria-label="MwanaCode editor" data-code-editor><?= e($starterCode) ?></textarea></div><div class="editor-help"><span><kbd>Ctrl</kbd> + <kbd>Enter</kbd> Run</span><span><kbd>Tab</kbd> Indent</span><button type="button" data-open-guide>Open language guide</button></div></section>
<section class="output-panel"><div class="output-tabs" role="tablist"><button type="button" class="active" role="tab" aria-selected="true" data-output-tab="console">Console</button><button type="button" role="tab" aria-selected="false" data-output-tab="drawing">Drawing canvas</button></div><div class="output-view active" data-output-view="console"><div class="output-placeholder" data-output-placeholder><?= icon('play') ?><h2>Program output</h2><p>Run the program to see text output or errors.</p></div><pre class="console-output" aria-live="polite" data-console-output></pre></div><div class="output-view drawing-view" data-output-view="drawing"><canvas width="700" height="520" data-drawing-canvas aria-label="Drawing created by MwanaCode turtle commands"></canvas><button type="button" class="canvas-clear" data-clear-canvas>Clear canvas</button></div></section>
</div><div class="code-lab-footer"><span><?= icon('shield-check') ?>MwanaCode parses a controlled command set and never evaluates arbitrary JavaScript.</span><a href="<?= e(url('projects.php')) ?>">Open project library</a></div>
</section>
<dialog class="guide-dialog" data-guide-dialog><form method="dialog"><button class="dialog-close" aria-label="Close language guide"><?= icon('x') ?></button></form><span class="eyebrow">MwanaCode reference</span><h2>Beginner programming commands</h2><div class="guide-grid"><div><code>SAY "text"</code><p>Displays text, a number or a variable value.</p></div><div><code>SET score = 5</code><p>Creates or changes a variable.</p></div><div><code>ADD score 1</code><p>Adds a number to a numeric variable.</p></div><div><code>REPEAT 4 ... END</code><p>Runs the enclosed block four times.</p></div><div><code>IF score &gt;= 5 ... END</code><p>Chooses a block using a condition.</p></div><div><code>MOVE 80 / TURN 90</code><p>Controls the drawing turtle.</p></div></div></dialog>
<?php require base_path('partials/footer.php'); ?>
