<?php
require_once __DIR__ . '/app/bootstrap.php';
if (!Database::tableExists('users')) redirect('setup.php');
$pageTitle = 'Privacy and safety';
$pageDescription = 'How CodeMwana protects learner information and limits unnecessary social features.';
$bodyClass = 'content-page';
require base_path('partials/header.php');
?>
<section class="content-hero"><div class="container"><span class="eyebrow">Privacy and safety</span><h1>Focused learning with limited data collection.</h1><p>CodeMwana stores information needed for account access, learning records and authorised reporting while excluding unnecessary public social features.</p></div></section>
<section class="section"><div class="container prose-shell"><article class="panel prose-panel"><h2>Information stored</h2><p>The platform stores account identity details, password hashes, school or learning-centre information, lesson progress, quiz attempts, enrolments, points, achievements, saved projects, project versions and an operational audit trail. Passwords are hashed and are never stored as readable text.</p><h2>How information is used</h2><p>Account information supports authentication and learner reports. Learning records provide continuity across sessions and help authorised teachers identify progress or areas requiring support. Administrators use audit records to review important platform operations.</p><h2>Safety by design</h2><p>CodeMwana does not provide public chat, direct messaging, public profile search, advertising, location tracking or photo sharing. Code Lab executes only the supported educational language and applies loop and instruction limits.</p><h2>Deployment responsibilities</h2><p>Institutions operating CodeMwana should use HTTPS, limit staff access, maintain backups, remove setup.php after installation, document retention and account-deletion procedures, and obtain appropriate parent, guardian or institutional approval for younger learners.</p></article><aside class="content-side"><section class="panel"><span class="eyebrow">Account controls</span><h2>Operational safeguards</h2><ul class="check-list"><li>Strong password requirements</li><li>Rate-limited failed sign-ins</li><li>Secure session regeneration</li><li>Role-based staff permissions</li><li>CSRF protection on write operations</li><li>Escaped user-generated output</li></ul></section></aside></div></section>
<?php require base_path('partials/footer.php'); ?>
