<?php
require_once __DIR__.'/app/bootstrap.php';require_auth();$user=current_user();$errors=[];
if(is_post()){verify_csrf();$action=(string)($_POST['action']??'');
 if($action==='profile'){$name=trim((string)($_POST['name']??''));$school=trim((string)($_POST['school_name']??''));$age=(string)($_POST['age_group']??'');if(mb_strlen($name)<3)$errors['name']='Enter a valid display name.';if(mb_strlen($school)<2)$errors['school_name']='Enter your school or learning centre.';if($user['role']==='learner'&&!in_array($age,['8-10','11-13','14-16','17+'],true))$errors['age_group']='Select a valid age group.';if(!$errors){Database::query('UPDATE users SET name=?,school_name=?,age_group=? WHERE id=?',[$name,$school,$user['role']==='learner'?$age:null,$user['id']]);activity('profile_updated');flash('success','Your profile information was updated.');redirect('profile.php');}}
 if($action==='password'){$current=(string)($_POST['current_password']??'');$password=(string)($_POST['password']??'');$confirm=(string)($_POST['password_confirmation']??'');$record=Database::fetch('SELECT password FROM users WHERE id=?',[$user['id']]);if(!$record||!password_verify($current,$record['password']))$errors['current_password']='The current password is incorrect.';if(strlen($password)<10||!preg_match('/[A-Z]/',$password)||!preg_match('/[a-z]/',$password)||!preg_match('/\d/',$password))$errors['password']='Use at least 10 characters with uppercase, lowercase and a number.';if($password!==$confirm)$errors['password_confirmation']='The passwords do not match.';if(!$errors){Database::query('UPDATE users SET password=? WHERE id=?',[password_hash($password,PASSWORD_DEFAULT),$user['id']]);activity('password_changed');flash('success','Your password was changed securely.');redirect('profile.php');}}
}
$user=Database::fetch('SELECT id,name,username,email,role,age_group,school_name,points,created_at,last_login_at FROM users WHERE id=?',[$user['id']]);$sessions=Database::fetchAll("SELECT action,created_at FROM activity_log WHERE user_id=? AND action IN ('signed_in','password_changed') ORDER BY created_at DESC LIMIT 8",[$user['id']]);
$pageTitle='Profile and security';$bodyClass='profile-page';require base_path('partials/header.php');
?>
<section class="workspace-section page-intro"><div><span class="eyebrow">Account settings</span><h1>Profile and security</h1><p>Keep account information accurate and protect access with a strong password.</p></div><div class="profile-summary"><span class="avatar large"><?= e(initials($user['name'])) ?></span><span><strong><?= e($user['name']) ?></strong><small><?= e($user['email']) ?></small></span></div></section>
<div class="settings-layout"><aside class="settings-nav panel"><a href="#profile" class="is-active"><?= icon('user') ?>Profile information</a><a href="#security"><?= icon('lock') ?>Password and security</a><a href="#activity"><?= icon('chart') ?>Account activity</a></aside><div class="settings-content">
<section class="panel settings-card" id="profile"><div class="panel-heading"><div><span class="eyebrow">Identity</span><h2>Profile information</h2><p>This information appears in your workspace and learning reports.</p></div></div><form method="post" class="form-stack"><?= csrf_field() ?><input type="hidden" name="action" value="profile"><div class="field"><label for="name">Display name</label><input id="name" name="name" value="<?= e($user['name']) ?>" required><?= validation_error($errors,'name') ?></div><div class="form-grid two"><div class="field"><label for="username">Username</label><input id="username" value="<?= e($user['username']) ?>" disabled><small class="field-hint">Usernames are permanent account identifiers.</small></div><div class="field"><label for="email">Email address</label><input id="email" value="<?= e($user['email']) ?>" disabled><small class="field-hint">An administrator can correct an account email.</small></div></div><div class="form-grid two"><div class="field"><label for="school_name">School or learning centre</label><input id="school_name" name="school_name" value="<?= e($user['school_name']) ?>" required><?= validation_error($errors,'school_name') ?></div><?php if($user['role']==='learner'): ?><div class="field"><label for="age_group">Age group</label><select id="age_group" name="age_group"><?php foreach(['8-10'=>'8–10 years','11-13'=>'11–13 years','14-16'=>'14–16 years','17+'=>'17 years or older'] as $value=>$label): ?><option value="<?= e($value) ?>" <?= $user['age_group']===$value?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select><?= validation_error($errors,'age_group') ?></div><?php endif; ?></div><button class="button" type="submit">Save profile changes</button></form></section>
<section class="panel settings-card" id="security"><div class="panel-heading"><div><span class="eyebrow">Account protection</span><h2>Change password</h2><p>Changing the password does not alter progress, projects or achievements.</p></div></div><form method="post" class="form-stack"><?= csrf_field() ?><input type="hidden" name="action" value="password"><div class="field"><label for="current_password">Current password</label><div class="password-field"><input id="current_password" name="current_password" type="password" autocomplete="current-password" required><button type="button" data-password-toggle="current_password">Show</button></div><?= validation_error($errors,'current_password') ?></div><div class="form-grid two"><div class="field"><label for="password">New password</label><div class="password-field"><input id="password" name="password" type="password" autocomplete="new-password" required data-password-strength><button type="button" data-password-toggle="password">Show</button></div><div class="password-meter" data-password-meter><span></span></div><?= validation_error($errors,'password') ?></div><div class="field"><label for="password_confirmation">Confirm new password</label><div class="password-field"><input id="password_confirmation" name="password_confirmation" type="password" autocomplete="new-password" required><button type="button" data-password-toggle="password_confirmation">Show</button></div><?= validation_error($errors,'password_confirmation') ?></div></div><button class="button" type="submit">Change password</button></form></section>
<section class="panel settings-card" id="activity"><div class="panel-heading"><div><span class="eyebrow">Security history</span><h2>Recent account activity</h2></div></div><div class="activity-table"><?php foreach($sessions as $session): ?><div><span><?= icon($session['action']==='signed_in'?'log-out':'lock') ?></span><div><strong><?= e(ucwords(str_replace('_',' ',$session['action']))) ?></strong><small><?= e(date('j M Y, H:i',strtotime($session['created_at']))) ?></small></div></div><?php endforeach; ?><?php if(!$sessions): ?><div class="compact-empty">No security activity has been recorded yet.</div><?php endif; ?></div></section>
</div></div>
<?php require base_path('partials/footer.php'); ?>
