<?php
require_once __DIR__.'/app/bootstrap.php';require_auth();$user=current_user();$data=Learning::dashboardData((int)$user['id']);$badges=Learning::badges((int)$user['id']);$courses=Learning::courses((int)$user['id']);$attempts=Database::fetchAll('SELECT qa.score,qa.passed,qa.created_at,l.title,l.slug,c.title AS course_title FROM quiz_attempts qa JOIN lessons l ON l.id=qa.lesson_id JOIN courses c ON c.id=l.course_id WHERE qa.user_id=? ORDER BY qa.created_at DESC LIMIT 12',[$user['id']]);
$pageTitle='Progress report';$bodyClass='progress-page';require base_path('partials/header.php');
?>
<section class="workspace-section page-intro"><div><span class="eyebrow">Learning analytics</span><h1>Your progress report</h1><p>Review completion, assessment performance, path progress and earned achievements from persisted account data.</p></div><button class="button button-secondary" type="button" onclick="window.print()"><?= icon('chart') ?>Print report</button></section>
<section class="metric-grid four"><article class="metric-card"><span class="metric-icon purple"><?= icon('book-open') ?></span><div><small>Completed lessons</small><strong><?= (int)$data['completed_lessons'] ?></strong></div></article><article class="metric-card"><span class="metric-icon green"><?= icon('chart') ?></span><div><small>Curriculum completion</small><strong><?= (int)$data['completion_percent'] ?>%</strong></div></article><article class="metric-card"><span class="metric-icon orange"><?= icon('check-circle') ?></span><div><small>Average best score</small><strong><?= (int)$data['average_score'] ?>%</strong></div></article><article class="metric-card"><span class="metric-icon blue"><?= icon('folder-code') ?></span><div><small>Projects created</small><strong><?= (int)$data['project_count'] ?></strong></div></article></section>
<div class="progress-layout"><section class="panel"><div class="panel-heading"><div><span class="eyebrow">Path completion</span><h2>Learning path progress</h2></div></div><div class="progress-course-list"><?php foreach($courses as $course):$percent=(int)$course['lesson_count']?(int)round((int)$course['completed_count']/(int)$course['lesson_count']*100):0; ?><a href="<?= e(url('course.php?course='.urlencode($course['slug']))) ?>"><span class="course-icon compact" style="--course:<?= e($course['colour']) ?>"><?= icon($course['icon']) ?></span><span><strong><?= e($course['title']) ?></strong><small><?= (int)$course['completed_count'] ?> of <?= (int)$course['lesson_count'] ?> lessons complete</small><span class="progress-track"><i style="width:<?= $percent ?>%"></i></span></span><b><?= $percent ?>%</b><?= icon('arrow-right') ?></a><?php endforeach; ?></div></section><section class="panel"><div class="panel-heading"><div><span class="eyebrow">Assessment history</span><h2>Recent quiz attempts</h2></div></div><?php if($attempts): ?><div class="attempt-list"><?php foreach($attempts as $attempt): ?><a href="<?= e(url('quiz.php?lesson='.urlencode($attempt['slug']))) ?>"><span class="score-badge <?= (int)$attempt['passed']?'success':'warning' ?>"><?= (int)$attempt['score'] ?>%</span><span><strong><?= e($attempt['title']) ?></strong><small><?= e($attempt['course_title']) ?> · <?= e(time_ago($attempt['created_at'])) ?></small></span><?= icon('arrow-right') ?></a><?php endforeach; ?></div><?php else: ?><div class="compact-empty">Quiz attempts will appear after you submit a lesson assessment.</div><?php endif; ?></section></div>
<section class="panel badge-panel" id="badges"><div class="panel-heading"><div><span class="eyebrow">Achievements</span><h2>Badges and milestones</h2></div><span class="count-badge"><?= count(array_filter($badges,fn($b)=>(int)$b['earned'])) ?> of <?= count($badges) ?> earned</span></div><div class="badge-grid"><?php foreach($badges as $badge): ?><article class="badge-card <?= (int)$badge['earned']?'earned':'locked' ?>"><span><?= icon($badge['icon']) ?></span><div><h3><?= e($badge['name']) ?></h3><p><?= e($badge['description']) ?></p><small><?= (int)$badge['earned']?'Earned '.e(date('j M Y',strtotime($badge['awarded_at']))):'+'.(int)$badge['points'].' points when earned' ?></small></div></article><?php endforeach; ?></div></section>
<?php require base_path('partials/footer.php'); ?>
