<?php
require_once __DIR__.'/app/bootstrap.php';require_auth();$user=current_user();
if(is_post()){verify_csrf();$action=(string)($_POST['action']??'');if($action==='delete'){$id=request_int('project_id');if(Learning::deleteProject($id,(int)$user['id']))flash('success','The project was removed from your library.');else flash('error','The project could not be found.');redirect('projects.php');}}
$projects=Learning::projects((int)$user['id']);
$pageTitle='My projects';$bodyClass='projects-page';require base_path('partials/header.php');
?>
<section class="workspace-section page-intro"><div><span class="eyebrow">Personal code library</span><h1>My projects</h1><p>Create original programs, continue previous work and keep automatic versions whenever saved code changes.</p></div><a class="button button-large" href="<?= e(url('playground.php')) ?>"><?= icon('plus') ?>New project</a></section>
<?php if($projects): ?><div class="project-toolbar"><div class="search-field"><?= icon('search') ?><label class="sr-only" for="project-search">Search projects</label><input id="project-search" aria-label="Search projects" data-filter-input data-filter-target=".project-card"></div><span><?= count($projects) ?> saved <?= count($projects)===1?'project':'projects' ?></span></div><section class="project-grid"><?php foreach($projects as $project): ?><article class="project-card" data-filter-item><div class="project-card-head"><span class="project-language"><?= icon('terminal') ?>MwanaCode</span><div class="dropdown" data-dropdown><button class="icon-button" type="button" data-dropdown-toggle aria-label="Project actions"><?= icon('more-horizontal') ?></button><div class="dropdown-menu"><a href="<?= e(url('playground.php?project='.(int)$project['id'])) ?>"><?= icon('edit') ?>Edit project</a><form method="post" data-confirm="Delete this project and its saved versions?"><?= csrf_field() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="project_id" value="<?= (int)$project['id'] ?>"><button type="submit"><?= icon('trash') ?>Delete project</button></form></div></div></div><div class="project-code-preview"><pre><code><?= e(implode("\n",array_slice(explode("\n",$project['code']),0,7))) ?></code></pre></div><div class="project-card-body"><h2><?= e($project['title']) ?></h2><div class="inline-meta"><span><?= icon('clock') ?>Updated <?= e(time_ago($project['updated_at'])) ?></span><span><?= icon('save') ?><?= (int)$project['version_count'] ?> previous <?= (int)$project['version_count']===1?'version':'versions' ?></span></div></div><a class="project-open" href="<?= e(url('playground.php?project='.(int)$project['id'])) ?>">Open in Code Lab<?= icon('arrow-right') ?></a></article><?php endforeach; ?></section><?php else: ?><section class="panel empty-panel large"><span class="empty-icon"><?= icon('folder-code') ?></span><h2>Your project library is ready</h2><p>Create a MwanaCode program or open a lesson challenge. Saving the program adds it here and later changes create version history.</p><a class="button button-large" href="<?= e(url('playground.php')) ?>"><?= icon('plus') ?>Create first project</a></section><?php endif; ?>
<?php require base_path('partials/footer.php'); ?>
