<?php
require_once dirname(__DIR__).'/app/bootstrap.php';require_role('admin');
$counts=['users'=>(int)Database::scalar('SELECT COUNT(*) FROM users'),'learners'=>(int)Database::scalar("SELECT COUNT(*) FROM users WHERE role='learner'"),'courses'=>(int)Database::scalar('SELECT COUNT(*) FROM courses'),'lessons'=>(int)Database::scalar('SELECT COUNT(*) FROM lessons'),'projects'=>(int)Database::scalar('SELECT COUNT(*) FROM projects'),'attempts'=>(int)Database::scalar('SELECT COUNT(*) FROM quiz_attempts'),'public_pages'=>Database::tableExists('public_pages')?(int)Database::scalar('SELECT COUNT(*) FROM public_pages'):0];
$recentUsers=Database::fetchAll('SELECT id,name,email,role,status,created_at FROM users ORDER BY created_at DESC LIMIT 8');$activity=Database::fetchAll('SELECT al.action,al.created_at,u.name FROM activity_log al LEFT JOIN users u ON u.id=al.user_id ORDER BY al.created_at DESC LIMIT 12');
$pageTitle='Platform administration';$bodyClass='admin-page';require base_path('partials/header.php');
?>
<section class="workspace-section page-intro"><div><span class="eyebrow">System control</span><h1>Platform administration</h1><p>Manage accounts, curriculum, public information and operational settings from one administration area.</p></div><div class="page-intro-actions"><a class="button button-secondary" href="<?= e(url('admin/users.php')) ?>"><?= icon('users') ?>Manage users</a><a class="button" href="<?= e(url('admin/public-pages.php')) ?>"><?= icon('edit') ?>Manage public pages</a></div></section>
<section class="metric-grid four"><article class="metric-card"><span class="metric-icon purple"><?= icon('users') ?></span><div><small>Total accounts</small><strong><?= $counts['users'] ?></strong></div></article><article class="metric-card"><span class="metric-icon green"><?= icon('book-open') ?></span><div><small>Published curriculum</small><strong><?= $counts['courses'] ?> <span>paths</span></strong></div></article><article class="metric-card"><span class="metric-icon orange"><?= icon('check-circle') ?></span><div><small>Quiz submissions</small><strong><?= $counts['attempts'] ?></strong></div></article><article class="metric-card"><span class="metric-icon blue"><?= icon('globe') ?></span><div><small>Public pages</small><strong><?= $counts['public_pages'] ?></strong></div></article></section>
<section class="admin-action-grid"><a href="<?= e(url('admin/users.php')) ?>"><span><?= icon('users') ?></span><div><strong>User and role management</strong><small>Create staff accounts, change roles and control account status.</small></div><?= icon('arrow-right') ?></a><a href="<?= e(url('admin/content.php')) ?>"><span><?= icon('book-open') ?></span><div><strong>Curriculum management</strong><small>Create and edit learning paths and lesson records.</small></div><?= icon('arrow-right') ?></a><a href="<?= e(url('admin/public-pages.php')) ?>"><span><?= icon('globe') ?></span><div><strong>Public page management</strong><small>Edit About, About Us, App, Developers, Contact, Privacy and Help content.</small></div><?= icon('arrow-right') ?></a><a href="<?= e(url('admin/settings.php')) ?>"><span><?= icon('settings') ?></span><div><strong>Platform settings</strong><small>Update branding, landing content and registration state.</small></div><?= icon('arrow-right') ?></a></section>
<div class="management-grid"><section class="panel"><div class="panel-heading"><div><span class="eyebrow">Account operations</span><h2>Recently created accounts</h2></div><a class="text-link" href="<?= e(url('admin/users.php')) ?>">View all<?= icon('arrow-right') ?></a></div><div class="data-table simple"><div class="data-table-head"><span>User</span><span>Role</span><span>Status</span><span>Created</span></div><?php foreach($recentUsers as $account): ?><div class="data-table-row"><span class="person-cell"><span class="avatar small"><?= e(initials($account['name'])) ?></span><span><strong><?= e($account['name']) ?></strong><small><?= e($account['email']) ?></small></span></span><span><span class="status-badge neutral"><?= e(ucfirst($account['role'])) ?></span></span><span><span class="status-badge <?= $account['status']==='active'?'success':'warning' ?>"><?= e(ucfirst($account['status'])) ?></span></span><span><?= e(date('j M Y',strtotime($account['created_at']))) ?></span></div><?php endforeach; ?></div></section><aside><section class="panel"><div class="panel-heading"><div><span class="eyebrow">Audit trail</span><h2>Recent operations</h2></div></div><ul class="activity-list"><?php foreach($activity as $item): ?><li><span></span><div><strong><?= e(ucwords(str_replace('_',' ',$item['action']))) ?></strong><small><?= e($item['name']??'System') ?> · <?= e(time_ago($item['created_at'])) ?></small></div></li><?php endforeach; ?></ul></section></aside></div>
<?php require base_path('partials/footer.php'); ?>